name: CMake on a Linux runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ci-linux:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build-type: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install build-essential clang cmake git &&
          mkdir build
      - name: CMake configure
        working-directory: build
        run: >
          flags="-Wall -Wextra -Wno-unused-parameter" &&
          if [ "${{ matrix.compiler }}" = "gcc" ]; then flags="${flags} -Wno-format-truncation"; fi &&
          if [ "${{ matrix.compiler }}" = "gcc" ]; then c_compiler="gcc" && cxx_compiler="g++"; else c_compiler="clang" && cxx_compiler="clang++"; fi &&
          cmake
          -DDNP3_TLS=OFF
          -DDNP3_TESTS=ON
          -DDNP3_EXAMPLES=ON
          -DDNP3_FUZZING=ON
          -DDNP3_JAVA=OFF
          -DDNP3_STATIC_LIBS=ON
          -DDNP3_COVERAGE=OFF
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DCMAKE_C_COMPILER="${c_compiler}"
          -DCMAKE_CXX_COMPILER="${cxx_compiler}"
          -DCMAKE_CXX_FLAGS="${flags}"
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/opendnp3-package
          ..
      - name: CMake build
        working-directory: build
        run: cmake --build . --parallel 4
      - name: Run C++ tests
        working-directory: build
        run: ctest -VV
      - name: Package build
        working-directory: build
        run: cmake --build . --target install
      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: opendnp3-linux-x64-${{ matrix.compiler }}-${{ matrix.build-type }}-${{ github.sha }}
          path: build/opendnp3-package
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install system dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install build-essential cmake curl git libssl-dev lcov &&
          mkdir build
      - name: CMake configure
        working-directory: build
        run: >
          cmake
          -DDNP3_TESTS=ON
          -DDNP3_COVERAGE=ON
          -DCMAKE_BUILD_TYPE=Debug
          ..
      - name: Build and run tests with code coverage
        if: ${{ matrix.coverage }} == "ON"
        working-directory: build
        run: cmake --build . --target coverage --parallel 4
      - name: Upload code coverage results
        if: false
        working-directory: build
        run: bash <(curl -s https://codecov.io/bash) -f coverage.info.cleaned
